### ISSUE TITLE
Linux build blows up on Travis CI

### ISSUE THREAD

**Issue by rtfeldman** [stoeffel/elm-interface-to-json#2]
[❌ Error on Travis Linux](https://travis-ci.org/rtfeldman/elm-css/jobs/230041059#L605-L609)
[✅ Success on Travis macOS](https://travis-ci.org/rtfeldman/elm-css/jobs/230041062)
[✅ Success on Appveyor Windows](https://ci.appveyor.com/project/rtfeldman/elm-css)

Works great on my local macOS too!

I wonder if this is reproducible on other CI environments... 🤔

**Comment by jwoudenberg** [comment]
I'll try this on Linux tomorrow, haven't done that yet.

**Comment by stoeffel** [comment]
@jwoudenberg did you look into this already?

**Comment by jwoudenberg** [comment]
I don't remember exactly what the problem was, but I believe we fixed this? @rtfeldman

**Comment by rtfeldman** [comment]
This is no longer reproducible! 🎉
