### ISSUE TITLE
Report both exposed and unexposed values

### ISSUE THREAD

**Issue by rtfeldman** [stoeffel/elm-interface-to-json#7]
As it has turned out, `node-test-runner` ended up wanting to know two things:

1. The exposed values of type `Test`
2. The *non-exposed* values of type `Test`

We use the latter to give the user an error if they forgot to expose any top-level values of type `Test`, so they can make sure to expose them.

Currently we are doing some janky JS parsing of `exposing` to get `#2`, but @eeue56 pointed out that `elm-interface-to-json` could provide both pieces of information after a single read of the `elmi` file.

I'm not sure what the output format should be for providing both pieces of info in one run, but as long as we can avoid needing a second read of the `elmi` file, it would be much faster than what we're currently doing!

**Comment by stoeffel** [comment]
unfortunately it is not possible to get any info about the not-exposed definitions. they aren't in the elmi. reading the elmi twice should be fine though since it's really fast. I will make it so that we can pass a query to the cli so that we don't need to read a huge json
